import AppKit
import IslandCore
import Observation

/// Recent clipboard items. Opt-in: nothing is read until the user turns it
/// on. Items password managers mark as concealed or transient are skipped,
/// and history lives only in memory (it's gone when the app quits).
@Observable
final class ClipboardService {
    private(set) var entries: [ClipboardEntry] = []
    private(set) var accessBehavior: NSPasteboard.AccessBehavior = NSPasteboard.general.accessBehavior

    @ObservationIgnored private let settings: SettingsStore
    @ObservationIgnored private var poll: Task<Void, Never>?
    @ObservationIgnored private var lastChange = NSPasteboard.general.changeCount
    @ObservationIgnored private var images: [UUID: NSImage] = [:]

    static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType",
    ]

    init(settings: SettingsStore) {
        self.settings = settings
    }

    func start() {
        whenChanged({ [settings] in settings.settings.clipboard.enabled }) { [weak self] _ in self?.apply() }
        apply()
    }

    private func apply() {
        if settings.settings.clipboard.enabled {
            guard poll == nil else { return }
            lastChange = NSPasteboard.general.changeCount
            // changeCount is a cheap check; contents are read only when it moves.
            poll = Task { [weak self] in
                while !Task.isCancelled {
                    try? await Task.sleep(for: .milliseconds(600))
                    self?.check()
                }
            }
            Log.info("clipboard history on")
        } else {
            poll?.cancel()
            poll = nil
            entries.removeAll()
            images.removeAll()
        }
    }

    func image(for entry: ClipboardEntry) -> NSImage? { images[entry.id] }

    /// Puts an entry back on the clipboard.
    func copy(_ entry: ClipboardEntry) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch entry.content {
        case .text(let t): pb.setString(t, forType: .string)
        case .link(let u): pb.writeObjects([u as NSURL]); pb.setString(u.absoluteString, forType: .string)
        case .files(let paths): pb.writeObjects(paths.map { URL(fileURLWithPath: $0) as NSURL })
        case .image: if let img = images[entry.id] { pb.writeObjects([img]) }
        }
        lastChange = pb.changeCount
        entries = ClipboardHistory.inserting(entry, into: entries, max: settings.settings.clipboard.historySize)
    }

    func remove(_ entry: ClipboardEntry) {
        entries.removeAll { $0.id == entry.id }
        images[entry.id] = nil
    }

    func clear() {
        entries.removeAll()
        images.removeAll()
    }

    private func check() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChange else { return }
        lastChange = pb.changeCount
        accessBehavior = pb.accessBehavior
        guard accessBehavior != .alwaysDeny else { return }
        let types = Set((pb.types ?? []).map(\.rawValue))
        if settings.settings.clipboard.ignoreConcealed, !types.isDisjoint(with: Self.concealedTypes) { return }
        let source = NSWorkspace.shared.frontmostApplication?.localizedName
        var entry: ClipboardEntry?
        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            let paths = urls.map(\.path)
            entry = ClipboardEntry(content: .files(paths), sourceApp: source, fingerprint: "files:" + paths.joined(separator: "|"))
        } else if let image = NSImage(pasteboard: pb), types.contains(NSPasteboard.PasteboardType.png.rawValue) || types.contains(NSPasteboard.PasteboardType.tiff.rawValue) {
            let size = image.size
            let e = ClipboardEntry(content: .image(width: Int(size.width), height: Int(size.height)), sourceApp: source,
                                   fingerprint: "image:\(pb.changeCount)")
            images[e.id] = image
            entry = e
        } else if let text = pb.string(forType: .string), !text.isEmpty {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            if let url = URL(string: trimmed), let scheme = url.scheme, ["http", "https"].contains(scheme), !trimmed.contains(" ") {
                entry = ClipboardEntry(content: .link(url), sourceApp: source, fingerprint: "link:" + trimmed)
            } else {
                entry = ClipboardEntry(content: .text(String(text.prefix(20_000))), sourceApp: source, fingerprint: "text:" + String(text.prefix(2_000)))
            }
        }
        guard let entry else { return }
        entries = ClipboardHistory.inserting(entry, into: entries, max: settings.settings.clipboard.historySize)
        let kept = Set(entries.map(\.id))
        images = images.filter { kept.contains($0.key) }
    }
}
